# Generated by Django 5.1.4 on 2024-12-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.PositiveIntegerField()),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=10)),
                ('vacinas', models.TextField(blank=True)),
            ],
        ),
    ]
